### ISSUE TITLE
Got error building on docker

### ISSUE THREAD

**Issue by stakrspace** [serge-medvedev/freeton-toolbox#1]
/opt/freeton-toolbox/validator # docker-compose build --build-arg EXTERNAL_UID=$(id -u) --build-arg EXTERNAL_GID=$(id -g) freeton-validator-dev
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by serge-medvedev** [comment]
Tell me please which version of docker-compose you're using.
